-- Seed portfolio data
INSERT INTO portfolio_sections (section_name, data) VALUES
('hero', '{"name": "Darpan Keni", "title": "Data Analyst", "subtitle": "Welcome to my portfolio", "description": "Transforming complex data into actionable insights through powerful visualizations and advanced analytics. Passionate about uncovering stories hidden in numbers.", "roles": ["Data Analyst", "Power BI Expert", "SQL Specialist", "Python Developer"], "resumeLink": "#", "contactLink": "#contact"}'),
('about', '{"name": "Darpan Keni", "initials": "DK", "location": "San Francisco, CA", "education": "B.S. Data Science", "experience": "3+ Years", "focus": "Business Intelligence", "bio1": "I am a dedicated Data Analyst with expertise in transforming complex datasets into actionable business insights.", "bio2": "With hands-on experience in Power BI, SQL, Excel, and Python, I specialize in building interactive dashboards, performing data cleaning and transformation, and developing automated reporting solutions that drive business decisions."}'),
('skills', '[{"name": "Power BI", "level": "Advanced", "percentage": 95, "color": "from-yellow-500 to-orange-500"}, {"name": "SQL", "level": "Expert", "percentage": 90, "color": "from-blue-500 to-cyan-500"}, {"name": "Excel", "level": "Advanced", "percentage": 92, "color": "from-green-500 to-emerald-500"}, {"name": "Python", "level": "Intermediate", "percentage": 75, "color": "from-yellow-400 to-blue-500"}, {"name": "Power Query", "level": "Advanced", "percentage": 88, "color": "from-purple-500 to-pink-500"}, {"name": "DAX", "level": "Advanced", "percentage": 85, "color": "from-cyan-500 to-blue-500"}]'),
('other_skills', '["Tableau", "Pandas", "NumPy", "PostgreSQL", "MySQL", "Azure", "SSIS", "Git"]'),
('experience', '[{"title": "Senior Data Analyst", "company": "TechCorp Inc.", "period": "2022 - Present", "color": "cyan"}, {"title": "Data Analyst", "company": "DataDriven Solutions", "period": "2020 - 2022", "color": "purple"}, {"title": "Business Intelligence Intern", "company": "Analytics Pro", "period": "2019 - 2020", "color": "pink"}]'),
('projects', '[{"title": "Sales Dashboard", "description": "Interactive Power BI dashboard tracking sales performance with real-time KPIs.", "colors": "from-neon-purple/20 to-neon-cyan/20", "iconColors": "from-neon-purple to-neon-cyan", "github": "#", "demo": "#"}, {"title": "Customer Analytics", "description": "SQL-based customer segmentation and churn prediction model with Python integration.", "colors": "from-neon-pink/20 to-neon-purple/20", "iconColors": "from-neon-pink to-neon-purple", "github": "#", "demo": "#"}, {"title": "Financial Reporting", "description": "Automated Excel reporting system with VBA macros and Power Query transformations.", "colors": "from-neon-cyan/20 to-neon-blue/20", "iconColors": "from-neon-cyan to-neon-blue", "github": "#", "demo": "#"}, {"title": "Predictive Analytics", "description": "Machine learning model for demand forecasting using Python and time series analysis.", "colors": "from-neon-blue/20 to-neon-purple/20", "iconColors": "from-neon-blue to-neon-purple", "github": "#", "demo": "#"}]'),
('certifications', '[{"name": "Microsoft Power BI Data Analyst", "issuer": "Microsoft", "year": "2023", "colors": "from-yellow-400 to-yellow-600"}, {"name": "Google Data Analytics", "issuer": "Google", "year": "2022", "colors": "from-blue-400 to-blue-600"}, {"name": "Tableau Desktop Specialist", "issuer": "Tableau", "year": "2022", "colors": "from-orange-400 to-red-500"}, {"name": "Azure Data Fundamentals", "issuer": "Microsoft", "year": "2021", "colors": "from-green-400 to-emerald-600"}]'),
('stats', '[{"value": 20, "suffix": "+", "label": "Projects Completed"}, {"value": 100, "suffix": "K+", "label": "Rows Analysed"}, {"value": 5, "suffix": "+", "label": "Certifications"}, {"value": 3, "suffix": "+", "label": "Years Experience"}]'),
('contact', '{"email": "darpan@example.com", "github": "#", "linkedin": "#", "twitter": "#"}');